version: '3.8'

services:
  packaging-service:
    build:
      context: ../..
      dockerfile: services/packaging-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - OUTPUT_DIR=/app/output
      - LOG_LEVEL=info
      - DATABASE_URL=postgres://qlp_user:qlp_password@postgres:5432/qlp_dev?sslmode=disable
    volumes:
      - packaging_output:/app/output
      - ./logs:/app/logs
    depends_on:
      - postgres
    networks:
      - qlp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=qlp_user
      - POSTGRES_PASSWORD=qlp_password
      - POSTGRES_DB=qlp_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - qlp-network
    restart: unless-stopped

volumes:
  packaging_output:
  postgres_data:

networks:
  qlp-network:
    driver: bridge